import "~/styles/globals.css";

import { type Metadata } from "next";
import { Manrope, Sora } from "next/font/google";

import { AppSidebar } from "~/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "~/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

const manrope = Manrope({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${manrope.variable} font-pretendard font-medium`}
    >
      <body>
        <SidebarProvider>
          {/* Desktop Sidebar - Hidden on mobile */}
          <div className="hidden md:block">
            <AppSidebar />
          </div>

          {/* Main Content */}
          <SidebarInset className="h-screen overflow-y-scroll p-8">
            {children}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
